---
title: "Data suggestions"
author: "R User Group"
date: "6 March 2017"
output: html_document
---

# Suggestions for open data to work with

## Martin

[Global Streamflow Characteristics Dataset](http://www.gloh2o.org/gscd/)

The Global Streamflow Characteristics Dataset (GSCD) consists of global maps of 17 streamflow characteristics, such as baseflow index, runoff coefficient, and flow percentiles, providing information about runoff behavior for the entire land surface including ungauged regions. The maps are unique in that they were derived using a data-driven (top down) approach based on streamflow observations from thousands of catchments around the globe, rather than using a physically-based (bottom up) process model.


[E-RUN version 1.1: Observational gridded runoff estimates for Europe](https://doi.pangaea.de/10.1594/PANGAEA.861371)

Observed monthly runoff rates are first tested for homogeneity and then related to gridded atmospheric variables (E-OBS version 12) using machine learning. The resulting statistical model is then used to estimate monthly runoff rates (December 1950 - December 2015) on a 0.5° x 0.5° grid. 

[E-OBS](http://www.ecad.eu/download/ensembles/ensembles.php)

Gridded precipitation and temperature for Europe 1950-present, 0.5° x 0.5° grid

[JRC Water portal](http://water.jrc.ec.europa.eu/waterportal)

Many layers potentially interesting

[European past floods](http://www.eea.europa.eu/data-and-maps/data/european-past-floods)

Dataset contains information on past floods in Europe since 1980, based on the reporting of EU Member States for the EU Floods Directive (2007/60/EC) and combined with information provided by relevant national authorities and global databases on natural hazards. Reported data have been assessed and processed by the ETC-ICM and the EEA.



## Strnda

[To be updated]

These are daily runoff data for EU catchments from 3 sources GRDC, EWA and CHMI, for GRDC and CHMI we have some basin spatial data as well (might be useful for the GIS-R part of our sessions)


## Roman

[CRU TS v. 3.24.01](https://crudata.uea.ac.uk/cru/data/hrg)

A gridded time-series dataset (01/1901 - 12/2015) in monthly step. It covers all land areas (excluding Antarctica) at 0.5° resolution. It contains variables such as precipitation, temperature, potential evapotranspiration etc. 


